# Site settings
title: Edinburgh Acro Festival
email: email@address.com
description: > # this means to ignore newlines until "baseurl:"
 Text about acro

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://edinburghacrofestival.github.io" # the base hostname & protocol for your site

twitter_username: #volnyio
github_username:  #volny

# Build settings
markdown: kramdown
